# Generated by scripts/make-formula.sh for each release. Install:
#   brew tap afiffattouh/handloom https://github.com/afiffattouh/handloom
#   brew install handloom
class Handloom < Formula
  desc "Run a team of coding agents on your own machines"
  homepage "https://github.com/afiffattouh/handloom"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.0/handloom_v0.1.0_darwin_arm64.tar.gz"
      sha256 "dbd31930df4eb5e92af276c89eec717d08edb18d3c23d0c60f9e014931ef1210"
    end
    on_intel do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.0/handloom_v0.1.0_darwin_amd64.tar.gz"
      sha256 "849165984abf4a94e92ad424a1b6e70bfa837551bbe69b94ece35097f3894c58"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.0/handloom_v0.1.0_linux_arm64.tar.gz"
      sha256 "00e33662600a9c2e0037ba6ca5e582aea0b6b2e7a5d6bb19dc84ca2ce44e3028"
    end
    on_intel do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.0/handloom_v0.1.0_linux_amd64.tar.gz"
      sha256 "863b1d327a274de565a0eadebf47e62cbaddd0ca85f1e0eceac6dd042b1279ba"
    end
  end

  depends_on "tmux" => :recommended

  def install
    bin.install "handloom"
    bin.install_symlink "handloom" => "hl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/handloom version")
  end
end
