# Generated by scripts/make-formula.sh for each release. Install:
#   brew tap afiffattouh/handloom https://github.com/afiffattouh/handloom
#   brew install handloom
class Handloom < Formula
  desc "Run a team of coding agents on your own machines"
  homepage "https://github.com/afiffattouh/handloom"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.3/handloom_v0.1.3_darwin_arm64.tar.gz"
      sha256 "d154488d9df14db0af29b7254a7cae67bc102e5c722911ec85d37d61503e513c"
    end
    on_intel do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.3/handloom_v0.1.3_darwin_amd64.tar.gz"
      sha256 "dfd79d93895ca6abad12cecc5cb3424f13f42c589ad0ecb78ed71dc0637650f2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.3/handloom_v0.1.3_linux_arm64.tar.gz"
      sha256 "1b8d2eb18c8a04dd6adfc560dc75514b5d47d91730b5df314943c98353e43549"
    end
    on_intel do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.3/handloom_v0.1.3_linux_amd64.tar.gz"
      sha256 "0d9266927a359e5d4851f2010fc02998cb383a458a8e880c32e0e83acaedcbca"
    end
  end

  depends_on "tmux" => :recommended

  def install
    bin.install "handloom"
    bin.install_symlink "handloom" => "hl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/handloom version")
  end
end
