# Generated by scripts/make-formula.sh for each release. Install:
#   brew tap afiffattouh/handloom https://github.com/afiffattouh/handloom
#   brew install handloom
class Handloom < Formula
  desc "Run a team of coding agents on your own machines"
  homepage "https://github.com/afiffattouh/handloom"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.2/handloom_v0.1.2_darwin_arm64.tar.gz"
      sha256 "86e3468eb04a1b47007ca2e89197fb6ba478747e6695737ff84a4b046e57cd28"
    end
    on_intel do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.2/handloom_v0.1.2_darwin_amd64.tar.gz"
      sha256 "cef27ebfaa36b00fdfbe5724ea13d1105e67b33f37cda76d1a278a9058bbfd05"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.2/handloom_v0.1.2_linux_arm64.tar.gz"
      sha256 "8cc09c9f0c929d5e58b69dd15ae87cf3dd4fb46041084d17dd04818f0b4215b5"
    end
    on_intel do
      url "https://github.com/afiffattouh/handloom/releases/download/v0.1.2/handloom_v0.1.2_linux_amd64.tar.gz"
      sha256 "bc6c978d323f405d96b827159ebd3079baa1435cf8ce9e5e94a0a8a507e88651"
    end
  end

  depends_on "tmux" => :recommended

  def install
    bin.install "handloom"
    bin.install_symlink "handloom" => "hl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/handloom version")
  end
end
