#!/usr/bin/env bash
# Writes the Homebrew formula for a release, from its checksums.txt.
#   scripts/make-formula.sh v0.1.0 dist/checksums.txt > Formula/handloom.rb
set -euo pipefail
VERSION="${1:?usage: make-formula.sh <version> <checksums.txt>}"; SUMS="${2:?checksums.txt}"
sum() { awk -v f="handloom_${VERSION}_$1.tar.gz" '$2 == f {print $1}' "$SUMS"; }
for t in darwin_arm64 darwin_amd64 linux_arm64 linux_amd64; do [ -n "$(sum $t)" ] || { echo "no checksum for $t in $SUMS" >&2; exit 1; }; done
cat <<RUBY
# Generated by scripts/make-formula.sh for each release. Install:
#   brew tap afiffattouh/handloom https://github.com/afiffattouh/handloom
#   brew install handloom
class Handloom < Formula
  desc "Run a team of coding agents on your own machines"
  homepage "https://github.com/afiffattouh/handloom"
  version "${VERSION#v}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/afiffattouh/handloom/releases/download/${VERSION}/handloom_${VERSION}_darwin_arm64.tar.gz"
      sha256 "$(sum darwin_arm64)"
    end
    on_intel do
      url "https://github.com/afiffattouh/handloom/releases/download/${VERSION}/handloom_${VERSION}_darwin_amd64.tar.gz"
      sha256 "$(sum darwin_amd64)"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/afiffattouh/handloom/releases/download/${VERSION}/handloom_${VERSION}_linux_arm64.tar.gz"
      sha256 "$(sum linux_arm64)"
    end
    on_intel do
      url "https://github.com/afiffattouh/handloom/releases/download/${VERSION}/handloom_${VERSION}_linux_amd64.tar.gz"
      sha256 "$(sum linux_amd64)"
    end
  end

  depends_on "tmux" => :recommended

  def install
    bin.install "handloom"
    bin.install_symlink "handloom" => "hl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/handloom version")
  end
end
RUBY
